# More human readable status codes for API actions and responses to be used in the API

NO_ERROR = "No Error"
UNAUTHORIZED = "Unauthorized"
FORBIDDEN = "Forbidden"
VALIDATION_ERROR = "Validation Error"
UNKNOWN_ERROR = "Unknown Error"
INVALID_INPUT = "Invalid Input"
DUPLICATE_KEY = "Duplicate Key"
DATA_NOT_FOUND = "Data Not Found"
DATA_CREATED = "Data Created"
DATA_UPDATED = "Data Updated"
DATA_DELETED = "Data Deleted"
DATA_FETCHED = "Data Fetched"
DATA_ALREADY_EXISTS = "Data Already Exists"
DATA_NOT_CREATED = "Data Not Created"
DATA_NOT_UPDATED = "Data Not Updated"
DATA_NOT_DELETED = "Data Not Deleted"
DUPLICATE_DATA_ITEM = "Duplicate Date Item"
NOT_FOUND = "Not Found"
INTERNAL_SERVER_ERROR = "Internal Server Error"
