version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Enables hot reloading
        - uvicorn_extras=--reload --use-colors --log-level debug
    env_file:
      - ".env"
    ports:
      # Get the port from the .env file
      - "${PORT}:80"
    volumes:
      # Mount the source code as a volume, for hot reloading
      - "./app:/app/app:ro"
      # Mount the prisma schema as a volume, for prisma migrations
      - "./prisma:/app/prisma:ro"
      # Mount the uploads folder as a volume, for file uploads
      - "./uploads:/app/uploads:rw"
